

.include <bsd.own.mk>

LIB=	be

#LIBDPLIBS+=	root /lib

CXXFLAGS= -Wno-multichar -Wno-old-style-cast -Wno-shadow -lroot

WARNS=		5


.include "${.CURDIR}/../../kits/app/Makefile.inc"
.include "${.CURDIR}/../../kits/interface/Makefile.inc"
.include "${.CURDIR}/../../kits/support/Makefile.inc"
.include <bsd.lib.mk>
