.include <bsd.own.mk>

LIB=	icon

.PATH: ${.CURDIR}/flat_icon \
       ${.CURDIR}/generic \
       ${.CURDIR}/message \
       ${.CURDIR}/shape \
       ${.CURDIR}/style \
       ${.CURDIR}/transformable \
       ${.CURDIR}/transformer

SRCS+=     Icon.cpp IconRenderer.cpp IconUtils.cpp

# flat_icon
SRCS+=     

# generic
SRCS+=     

# message
SRCS+=     

# shape
SRCS+=     

# style
SRCS+=     

# transformable
SRCS+=     

# transformer
SRCS+=     

CXXFLAGS= -Wno-multichar -Wno-old-style-cast -Wno-shadow
CPPFLAGS+= -I${.CURDIR}

#LDFLAGS= -L/usr/pkg/lib -rpath=/usr/pkg/lib -lroot -licudata -licui18n -licuio -licuuc -lz -lzstd


WARNS=		5


#.include "${.CURDIR}/../../kits/app/Makefile.inc"


.include <bsd.lib.mk>
